<a href="https://colab.research.google.com/github/SantiagoMaya10/PPI-MayaRestrepo-2024-1s/blob/main/SI02_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## «*Olvidaba que en todo combate entre el fanatismo y el sentido común, pocas veces logra este último imponerse*».
### [Marguerite Yourcenar](https://es.wikipedia.org/wiki/Marguerite_Yourcenar)

# SI02 NumPy

Actividad individual.

Resuelva los siguientes ejercicios con códigos que se ajusten al PEP8. Recuerde incluir los comentarios en el código y documentar las funciones con docstrings al estilo de Google.

**Importante:**

**no se permite la utilización de ciclos (for or while) para resolver los ejercicios.**

**todos los ejercicios deben ser resueltos con NumPy.**

## Ejercicio 00

Cree el arreglo_00 de 15 **columnas** y 1000 **filas** de la siguiente manera:

* cinco columnas con números aleatorios provenientes de una distribución normal de media 0 y desviación típica 1. Utilice como semilla el número de su documento de identidad sumado con el número de la columna.

* cinco columnas con números aleatorios enteros en los siguientes intervalos: 200 a 300, 400 a 600, 0 a 360, 100 a 900, y 1000 a 2000. Utilice como semilla el número de su documento de identidad.

* cinco columnas con números aleatorios binarios (0,1)

Muestre el resultado y las características del arreglo.

In [54]:
# Escriba aquí su códig
import numpy as np

def crear_arreglo():
    """
    Crea un arreglo de 1000 filas y 15 columnas con números aleatorios siguiendo las siguientes especificaciones:

    - Las primeras cinco columnas contienen números aleatorios provenientes de una distribución normal con media 0 y desviación típica 1.
    - Las siguientes cinco columnas contienen números aleatorios enteros en diferentes intervalos: 200 a 300, 400 a 600, 0 a 360, 100 a 900, y 1000 a 2000.
    - Las últimas cinco columnas contienen números aleatorios binarios (0 o 1).

    Returns:
    numpy.ndarray: Un arreglo de dimensiones (1000, 15) con los números aleatorios generados según las especificaciones.
    """
    # Semilla para generar números aleatorios
    semilla = 1017276204  # Número de documento de identidad

    # Generar cinco columnas con números aleatorios de distribución normal
    np.random.seed(semilla+1)
    normal_column_1 = np.random.normal(0, 1, size=(1000, 1))
    np.random.seed(semilla+2)
    normal_column_2 = np.random.normal(0, 1, size=(1000, 1))
    np.random.seed(semilla+3)
    normal_column_3 = np.random.normal(0, 1, size=(1000, 1))
    np.random.seed(semilla+4)
    normal_column_4 = np.random.normal(0, 1, size=(1000, 1))
    np.random.seed(semilla+5)
    normal_column_5 = np.random.normal(0, 1, size=(1000, 1))

    normal_columns = np.column_stack([normal_column_1,
                               normal_column_2,
                               normal_column_3,
                               normal_column_4,
                               normal_column_5])
    print("Foma de la sprimeras 5 columnas: ")
    print(normal_columns.shape)


    # Generar cinco columnas con números aleatorios enteros en diferentes intervalos
    np.random.seed(semilla)
    entero_columns = np.column_stack([
        np.random.randint(200, 301, size=1000),  # Intervalo 200 a 300
        np.random.randint(400, 601, size=1000),  # Intervalo 400 a 600
        np.random.randint(0, 361, size=1000),    # Intervalo 0 a 360
        np.random.randint(100, 901, size=1000),  # Intervalo 100 a 900
        np.random.randint(1000, 2001, size=1000) # Intervalo 1000 a 2000
    ])
    print("Foma de la segundas 5 columnas: ")
    print(normal_columns.shape)


    # Generar cinco columnas con números aleatorios binarios
    binario_columns = np.random.randint(0, 2, size=(1000, 5))
    print("Foma de la terceras 5 columnas: ")
    print(normal_columns.shape)

    # Concatenar las columnas para formar el arreglo completo
    arreglo_00 = np.column_stack([normal_columns, entero_columns, binario_columns])

    return arreglo_00

# Crear el arreglo
arreglo_00 = crear_arreglo()

# Mostrar el arreglo y sus características
print("Arreglo:")
print(arreglo_00)
print("\nDimensiones del arreglo:", arreglo_00.shape)
print("Tipo de datos del arreglo:", arreglo_00.dtype)
print("Valor máximo en el arreglo:", np.max(arreglo_00))
print("Valor mínimo en el arreglo:", np.min(arreglo_00))


Foma de la sprimeras 5 columnas: 
(1000, 5)
Foma de la segundas 5 columnas: 
(1000, 5)
Foma de la terceras 5 columnas: 
(1000, 5)
Arreglo:
[[ 1.82228728  0.10334738  0.31070983 ...  1.          0.
   1.        ]
 [ 1.62350749  0.96107289  1.13073118 ...  0.          1.
   0.        ]
 [ 0.76672338  1.52463954 -0.88588701 ...  0.          0.
   1.        ]
 ...
 [-0.92884616  1.23811536  0.47602158 ...  0.          0.
   0.        ]
 [-0.20577863 -0.03659333  0.77829626 ...  1.          1.
   1.        ]
 [-0.33570516 -1.80734874 -1.39017678 ...  1.          0.
   1.        ]]

Dimensiones del arreglo: (1000, 15)
Tipo de datos del arreglo: float64
Valor máximo en el arreglo: 1997.0
Valor mínimo en el arreglo: -3.434243141672083


## Ejercicio 01

Cree dos arreglos, de 15 columnas y 20 filas cada uno, a partir del arreglo_00.

Calcule el producto elemento a elemento entre los dos arreglos creados

Muestre el resultado y las características del arreglo que contiene el producto elemento a elemento.

In [55]:
# Escriba aquí su código

import numpy as np

# Se extraen las primeras 20 filas del arreglo_00 y se obtiene una submatrix de 20x15
submatrix_1 = arreglo_00[0:20]
print(f"Dimensiones submatriz 1: {submatrix_1.shape}")

# Se extraen las filas de la 20 a la 40 del arreglo_00 y se obtiene una submatrix de 20x15
submatrix_2 = arreglo_00[20:40]
print(f"Dimensiones submatriz 2: {submatrix_2.shape}")

# Se multiplican elemento a elemento
matriz_final = submatrix_1 * submatrix_2

print(f"Dimensiones de la submatriz obtenida\
 después de multiplicar: {matriz_final.shape}")

print("\nDimensiones de la matrixz:", matriz_final.shape)
print("Tipo de datos de la matriz:", matriz_final.dtype)
print("Valor máximo en la matriz:", np.max(matriz_final))
print("Valor mínimo en la amtriz:", np.min(matriz_final))

Dimensiones submatriz 1: (20, 15)
Dimensiones submatriz 2: (20, 15)
Dimensiones de la submatriz obtenida después de multiplicar: (20, 15)

Dimensiones de la matrixz: (20, 15)
Tipo de datos de la matriz: float64
Valor máximo en la matriz: 3478120.0
Valor mínimo en la amtriz: -2.9528470858958733


## Ejercicio 02

Cree dos arreglos, de 10 columnas y 10 filas cada uno, a partir del arreglo_00.

Calcule el producto matricial entre los dos arreglos creados

Muestre el resultado y las características del arreglo que contiene el producto matricial.

In [72]:
# Escriba aquí su código

import numpy as np

print(arreglo_00.shape)

# Se extraen las primeras 10 filas del arreglo_00 y luego se aplica slicing para obtener 10 columnas
submatrix_1 = arreglo_00[0:10][0:,0:10]
submatrix_2 = arreglo_00[10:20][0:,0:10]

print(f"Dimensiones submatriz 1: {submatrix_1.shape}")
print(f"Dimensiones submatriz 2: {submatrix_2.shape}")

matrix_product = np.matmul(submatrix_1, submatrix_2)


print(f"Dimensiones de la submatriz obtenida\
 después de multiplicar matricialmente: {matrix_product.shape}")

print("\nDimensiones de la matriz:", matrix_product.shape)
print("Tipo de datos de la matriz:", matrix_product.dtype)
print("Valor máximo en la matriz:", np.max(matrix_product))
print("Valor mínimo en la amtriz:", np.min(matrix_product))


(1000, 15)
Dimensiones submatriz 1: (10, 10)
Dimensiones submatriz 2: (10, 10)
Dimensiones de la submatriz obtenida después de multiplicar matricialmente: (10, 10)

Dimensiones de la matriz: (10, 10)
Tipo de datos de la matriz: float64
Valor máximo en la matriz: 4596897.846962875
Valor mínimo en la amtriz: -4027.6173890144914


## Ejercicio 03

Cree un arreglo, de 15 columnas y 10 filas, a partir del arreglo_00.

Calcule y muestre la suma de cada una de las columnas y de cada una de las filas.

In [79]:
# Escriba aquí su código

# Import numpy
import numpy as np

# Se extraen las primeras 10 filas del arreglo_00
submatrix = arreglo_00[0:10]
print(f"Dimensiones submatriz: {submatrix.shape}")

# Calcular la suma de cada columna
suma_columnas = np.sum(submatrix, axis=0)

# Calcular la suma de cada fila
suma_filas = np.sum(submatrix, axis=1)

# Mostrar resultados
print("Suma de cada columna:")
print(suma_columnas)
print("Suma de cada fila:")
print(suma_filas)



Dimensiones submatriz: (10, 15)
Suma de cada columna:
[ 6.24075679e+00  2.56298612e+00  1.14411375e+00  5.70646225e+00
 -1.27345502e-01  2.63600000e+03  5.11300000e+03  1.81200000e+03
  5.03700000e+03  1.39300000e+04  7.00000000e+00  5.00000000e+00
  5.00000000e+00  5.00000000e+00  5.00000000e+00]
Suma de cada fila:
[2672.20636721 3156.60716772 2466.15746407 2615.59741239 3360.5573504
 2447.80424569 2569.73270014 3071.11425737 2938.50456053 3272.24544789]


## Ejercicio 04

Utilice el arreglo creado en el ejercicio anterior. Reconvierta el arreglo a uno de dimensión 5 columnas y 30 filas.

A partir de ese arreglo cree otro nuevo en el cual cada uno de los elementos de las filas es mayor que el promedio de la respectiva columna.

Muestre el arreglo obtenido y sus características.

In [83]:
# Escriba aquí su código

# Rconvertimos de 10*15 a 30*5
arreglo_30x5 = submatrix.reshape(30, 5)

print(f"Dimensiones submatriz: {arreglo_30x5.shape}")

# Calcular el promedio de cada columna
promedio_columnas = np.mean(arreglo_30x5, axis=0)

# Crear un arreglo booleano indicando si cada elemento es mayor que el promedio de su columna
mayor_que_promedio = arreglo_30x5 > promedio_columnas

# Crear un nuevo arreglo con los elementos que son mayores que el promedio de su columna
nuevo_arreglo = np.where(mayor_que_promedio, arreglo_30x5, 0)

# Mostrar el nuevo arreglo
print("Nuevo arreglo:")
print(nuevo_arreglo)

Dimensiones submatriz: (30, 5)
Nuevo arreglo:
[[  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [ 76  77  78  79  80]
 [ 81  82  83  84  85]
 [ 86  87  88  89  90]
 [ 91  92  93  94  95]
 [ 96  97  98  99 100]
 [101 102 103 104 105]
 [106 107 108 109 110]
 [111 112 113 114 115]
 [116 117 118 119 120]
 [121 122 123 124 125]
 [126 127 128 129 130]
 [131 132 133 134 135]
 [136 137 138 139 140]
 [141 142 143 144 145]
 [146 147 148 149 150]]


## Ejercicio 05

Utilice el arreglo creado en el ejercicio 03.

Ordene cada columna de forma descendente, de mayor a menor, de forma independiente. Luego cree un nuevo arreglo con la concatenación de todas las columnas ordenadas.

Muestre el resultado y las características del arreglo.

In [87]:
# Escriba aquí su código

import numpy as np


submatrix = arreglo_00[0:10]
print(f"Dimensiones submatriz: {submatrix.shape}")
# Ordenar cada columna de forma descendente
columnas_ordenadas_desc = np.sort(submatrix, axis=0)[::-1]

# Concatenar las columnas ordenadas para formar un nuevo arreglo
nuevo_arreglo = columnas_ordenadas_desc.flatten()

# Mostrar el nuevo arreglo
print("Nuevo arreglo con columnas ordenadas de forma descendente:")
print(nuevo_arreglo)
print(f"Dimensiones del nuevo arreglo {nuevo_arreglo.shape}")
print("Tipo de datos del nuevo arreglo:", nuevo_arreglo.dtype)
print("Valor máximo del nuevo arreglo:", np.max(nuevo_arreglo))
print("Valor mínimo del nuevo arreglo:", np.min(nuevo_arreglo))

Dimensiones submatriz: (10, 15)
Nuevo arreglo con columnas ordenadas de forma descendente:
[ 1.82228728e+00  1.96534960e+00  1.13073118e+00  2.23747485e+00
  6.85409007e-01  2.96000000e+02  5.73000000e+02  3.48000000e+02
  8.72000000e+02  1.95400000e+03  1.00000000e+00  1.00000000e+00
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.73624873e+00
  1.52463954e+00  9.17828716e-01  1.87951890e+00  6.30451771e-01
  2.91000000e+02  5.72000000e+02  3.16000000e+02  7.40000000e+02
  1.81200000e+03  1.00000000e+00  1.00000000e+00  1.00000000e+00
  1.00000000e+00  1.00000000e+00  1.67135274e+00  1.20853097e+00
  6.17746939e-01  1.74843767e+00  3.56164600e-01  2.89000000e+02
  5.36000000e+02  2.00000000e+02  6.62000000e+02  1.62100000e+03
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00
  1.00000000e+00  1.62350749e+00  9.61072890e-01  3.10709829e-01
  6.57413562e-01  2.27921025e-01  2.80000000e+02  5.28000000e+02
  1.77000000e+02  5.05000000e+02  1.42600000e+03  1.00000000e+00

## Ejercicio 06

Cree un arreglo, de 9 columnas y 9 filas, a partir del arreglo_00.

Agregue una nueva columna al final del arreglo que contenga la suma de cada una de las filas y otra columna que contenga el promedio de las nueve columnas originales del arreglo.

Muestre el resultado y las características del arreglo.

In [92]:
# Escriba aquí su código

# Se seleccionan 9 dilas y luego se seleccionan 9 columans de cada una de esas filas
arreglo_9x9 = arreglo_00[0:9][0:,0:9]

print(f"Dimensiones arreglo_9x9: {arreglo_9x9.shape}")


# Calcular la suma de cada fila
suma_filas = np.sum(arreglo_9x9, axis=1)

# Calcular el promedio de las nueve columnas originales
promedio_columnas = np.mean(arreglo_9x9, axis=0)

arreglo_final = np.column_stack([arreglo_9x9, suma_filas, promedio_columnas])

# Mostrar el nuevo arreglo final
print(f"Nuevo arreglo {arreglo_final}")
print(f"Dimensiones del nuevo arreglo {arreglo_final.shape}")
print("Tipo de datos del nuevo arreglo:", arreglo_final.dtype)
print("Valor máximo del nuevo arreglo:", np.max(arreglo_final))
print("Valor mínimo del nuevo arreglo:", np.min(arreglo_final))

Dimensiones arreglo_9x9: (9, 9)
Nuevo arreglo [[ 1.82228728e+00  1.03347384e-01  3.10709829e-01  2.84613704e-01
   6.85409007e-01  2.91000000e+02  5.36000000e+02  1.34000000e+02
   3.40000000e+02  1.30420637e+03  6.90954105e-01]
 [ 1.62350749e+00  9.61072890e-01  1.13073118e+00  2.03426808e-01
  -3.11570639e-01  2.89000000e+02  4.47000000e+02  9.90000000e+01
   5.05000000e+02  1.34360717e+03  1.50495017e-01]
 [ 7.66723384e-01  1.52463954e+00 -8.85887015e-01  1.48430850e-01
  -3.96442692e-01  2.78000000e+02  5.72000000e+02  3.48000000e+02
   2.30000000e+02  1.42915746e+03  1.37422956e-01]
 [ 9.89657643e-02 -6.08726828e-01 -7.36515891e-01  2.23747485e+00
  -3.93785502e-01  2.34000000e+02  5.28000000e+02  1.70000000e+02
   4.66000000e+02  1.39859741e+03  4.25215928e-01]
 [-2.48982011e-01 -2.97997391e+00 -2.69443260e-03  1.74843767e+00
   4.05630958e-02  2.37000000e+02  4.59000000e+02  1.70000000e+02
   8.72000000e+02  1.73655735e+03 -3.94740586e-02]
 [ 1.73624873e+00  8.27223677e-01 -3.47

## Ejercicio 07

A partir de la columna del arreglo 00 que contiene los números enteros entre 0 y 360, genere un nuevo arreglo de 10 x 100.

Genere un nuevo arreglo en el que cada valor corresponda a la conversión de grados sexagesimales a radianes del arreglo que acaba de crear

Muestre el resultado y las características del arreglo.

In [99]:
# Escriba aquí su código

# Crear una máscara booleana para identificar las columnas que cumplen con la condición
mascara = np.logical_and(arreglo_00 > 0, arreglo_00 < 360)

# Filtrar las columnas que cumplen con la condición
arreglo_filtrado = arreglo_00[:, mascara.any(axis=0)]
arreglo_radianes = np.radians(arreglo_filtrado)

# Mostrar el resultado y las características del arreglo
print("Nuevo arreglo de 10x100:")
print(arreglo_filtrado)
print("\nArreglo de radianes:")
print(arreglo_radianes)
print("\nDimensiones del arreglo de radianes:", arreglo_radianes.shape)
print("Tipo de datos del arreglo de radianes:", arreglo_radianes.dtype)
print("Valor máximo en el arreglo de radianes:", np.max(arreglo_radianes))
print("Valor mínimo en el arreglo de radianes:", np.min(arreglo_radianes))

print(f"Dimensiones arreglo_9x9: {arreglo_filtrado.shape}")
print(arreglo_filtrado)




Nuevo arreglo de 10x100:
[[ 1.82228728  0.10334738  0.31070983 ...  1.          0.
   1.        ]
 [ 1.62350749  0.96107289  1.13073118 ...  0.          1.
   0.        ]
 [ 0.76672338  1.52463954 -0.88588701 ...  0.          0.
   1.        ]
 ...
 [-0.92884616  1.23811536  0.47602158 ...  0.          0.
   0.        ]
 [-0.20577863 -0.03659333  0.77829626 ...  1.          1.
   1.        ]
 [-0.33570516 -1.80734874 -1.39017678 ...  1.          0.
   1.        ]]

Arreglo de radianes:
[[ 0.03180491  0.00180375  0.00542291 ...  0.01745329  0.
   0.01745329]
 [ 0.02833555  0.01677389  0.01973498 ...  0.          0.01745329
   0.        ]
 [ 0.01338185  0.02660998 -0.01546165 ...  0.          0.
   0.01745329]
 ...
 [-0.01621142  0.02160919  0.00830814 ...  0.          0.
   0.        ]
 [-0.00359151 -0.00063867  0.01358383 ...  0.01745329  0.01745329
   0.01745329]
 [-0.00585916 -0.03154419 -0.02426316 ...  0.01745329  0.
   0.01745329]]

Dimensiones del arreglo de radianes: (1000, 13)


## Ejercicio 08

Cree un arreglo, de 15 columnas y 15 filas seleccionadas aleatoriamente (utilice el número de su documento de identidad como semilla), a partir del arreglo_00.

Calcule y muestre el determinante del arreglo, la transpuesta y la inversa.

In [100]:
# Escriba aquí su código
import numpy as np

# Semilla para generar números aleatorios
semilla = 1017276204  # Número de documento de identidad

# Utilizar la semilla para seleccionar aleatoriamente 15 filas del arreglo
np.random.seed(semilla)
filas_seleccionadas = np.random.choice(arreglo_00.shape[0], size=15, replace=False)
arreglo_seleccionado = arreglo_00[filas_seleccionadas]

# Calcular el determinante del arreglo
determinante = np.linalg.det(arreglo_seleccionado)

# Calcular la transpuesta del arreglo
transpuesta = arreglo_seleccionado.T

# Calcular la inversa del arreglo
inversa = np.linalg.inv(arreglo_seleccionado)

# Mostrar los resultados
print("Arreglo seleccionado de 15x15:")
print(arreglo_seleccionado)
print("\nDeterminante del arreglo:", determinante)
print("\nTranspuesta del arreglo:")
print(transpuesta)
print("\nInversa del arreglo:")
print(inversa)


Arreglo seleccionado de 15x15:
[[-8.93954659e-01  1.37088535e+00  4.30971571e-01  1.07600344e+00
  -1.32893411e+00  2.23000000e+02  4.35000000e+02  2.36000000e+02
   5.40000000e+02  1.03200000e+03  0.00000000e+00  1.00000000e+00
   0.00000000e+00  1.00000000e+00  1.00000000e+00]
 [-1.63282527e+00  6.35492167e-01  5.00840085e-01  4.08966814e-01
   7.48620841e-01  2.70000000e+02  4.23000000e+02  8.20000000e+01
   1.97000000e+02  1.51500000e+03  0.00000000e+00  1.00000000e+00
   1.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 1.14093221e-01 -4.21085336e-01 -4.12196978e-01  1.02061536e-01
   2.77813168e-01  2.15000000e+02  4.08000000e+02  8.80000000e+01
   7.05000000e+02  1.66600000e+03  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [-1.92923464e+00 -2.09847357e+00  9.97322772e-01  2.99575804e+00
   8.33605412e-02  3.00000000e+02  4.81000000e+02  4.10000000e+01
   1.20000000e+02  1.48500000e+03  0.00000000e+00  1.00000000e+00
   1.00000000e+00  1.000

## Ejercicio 09

Cree un arreglo, de 8 columnas y  8 filas, ambas seleccionadas aleatoriamente (utilice el número de su documento de identidad como semilla), a partir del arreglo_00.

Luego cree un arreglo de dimensión 1x8 con número reales aleatorios en el intervalo 0,10 (utilice el número de su documento de identidad como semilla).

Asuma que el primer arreglo representa los coeficientes de un sistema de ecuaciones lineales, y el segundo arreglo contiene las respectivas constantes. Encuentre la solución al sistema utilizando funciones de álgebra lineal de NumPy.

Muestre el valor de cada una de las variables que resuelve el sistema de ecuaciones.

In [ ]:
# Escriba aquí su código
